added basic profile page
GrinnellAppDev/Publications-Android pull request #18
Opened 2016-12-06 06:09 UTC by PsychicNoodles

Implemented the CoordinatorLayout, RecyclerView, and an extremely basic CardView for profiles. Fully implemented ViewHolder for the cards will be in a later PR.

2016-12-06 06:10 UTC, PsychicNoodles commented
![screenshot_20161206-000823](https://cloud.githubusercontent.com/assets/1944082/20914917/549ee072-bb48-11e6-9305-ec70db23e30b.png)
![screenshot_20161206-000844](https://cloud.githubusercontent.com/assets/1944082/20914920/5605bf1c-bb48-11e6-8b00-c7dd7deb656b.png)

2016-12-06 22:57 UTC, PsychicNoodles commented
![screenshot_20161206-165540](https://cloud.githubusercontent.com/assets/1944082/20947499/1212f7c4-bbd5-11e6-94f9-a21f0108351a.png)
![screenshot_20161206-165551](https://cloud.githubusercontent.com/assets/1944082/20947502/131fd9ac-bbd5-11e6-80e0-0b11c8e911b6.png)

2016-12-07 03:35 UTC, LarryAsante commented on app/build.gradle.orig
> +apply plugin: 'com.android.application'
This file should not be in here

2016-12-07 03:36 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/grinnell_publications_android/Activities/MainActivity.java
> +        drawerLayout.openDrawer(GravityCompat.START);
Nit-picking: Use a static import for this.  This should read `drawerLayout.openDrawer(START);`. See above for the import statement.

2016-12-07 03:37 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/grinnell_publications_android/Activities/MainActivity.java
> +import android.support.v4.view.GravityCompat;
Change this to `import static android.support.v4.view.GravityCompat.START;` and move this to the bottom of the import statements

2016-12-07 03:38 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/grinnell_publications_android/Adapters/ArticleAdapter.java
> +        ArticleViewHolder vh = new ArticleViewHolder(v);
Please use proper variable names

2016-12-07 03:38 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/grinnell_publications_android/Adapters/ArticleAdapter.java
> +        View v = LayoutInflater.from(parent.getContext())
Use proper variable naming

2016-12-07 03:39 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/grinnell_publications_android/Fragments/ExpandedArticleFragment.java
> +        setHeaderText("Sample title");
Even though this is a dummy string, extract this text into the strings.xml and reference it from there.  Please label it as such in the strings.xml file

2016-12-07 03:39 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/grinnell_publications_android/Fragments/ExpandedArticleFragment.java
> +        setContentText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris feugiat diam sollicitudin est semper, eu porta libero pulvinar. Aenean at lacus rhoncus, pharetra elit ut, ultr
Same here

2016-12-07 03:39 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/grinnell_publications_android/Fragments/ExpandedArticleFragment.java
> +    private ImageView mHeaderImage;
I like the constistency in your variable naming! 👍

2016-12-07 03:42 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/grinnell_publications_android/Fragments/ExpandedArticleFragment.java
> +        mHeaderImage = (ImageView) expandedArticleFragment.findViewById(R.id.header_image);
Our `onCreateView(...)` is getting cluttered. Extract all of the view bindings here into a method, say `public void bindView()` and call that method in `initializeUI()`, above `loadPlaceHolderData()`

2016-12-07 03:42 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/grinnell_publications_android/Fragments/ExpandedArticleFragment.java
> +                Snackbar.make(v, "Sample article added to Favorites", Snackbar.LENGTH_SHORT).show();
nit: Use static import

2016-12-07 03:43 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/grinnell_publications_android/Fragments/ExpandedArticleFragment.java
> +                Snackbar.make(v, "Sample article added to Favorites", Snackbar.LENGTH_SHORT).show();
Extract string into the `strings.xml` file

2016-12-07 03:43 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/grinnell_publications_android/Fragments/ExpandedArticleFragment.java
> +            public void onClick(View v) {
I know this was the variable name given on the method's call but please change it to something like `View view`. It's more descriptive

2016-12-07 03:44 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/grinnell_publications_android/Fragments/ExpandedArticleFragment.java
> +        Drawable defaultImage = ContextCompat.getDrawable(getContext(), R.drawable.grinnell_gates);
You could also use a static import for `getDrawable()` as it is a static method of the `ContextCompat` class

2016-12-07 03:47 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/grinnell_publications_android/Fragments/ExpandedArticleFragment.java
> +    private Toolbar mArticleToolbar;
Please destroy all of these member variables in Fragment's `onDestroyView()` as it allows the fragment to clean up resources associated with its View. That way, we're not leaking any memory references on the Fragment's destruction.

2016-12-07 03:47 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/grinnell_publications_android/Fragments/ProfileFragment.java
> +    private RecyclerView mRecycler;
Please destroy all of these member variables in Fragment's `onDestroyView()` as it allows the fragment to clean up resources associated with its View. That way, we're not leaking any memory references on the Fragment's destruction.

2016-12-07 03:48 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/grinnell_publications_android/Fragments/ProfileFragment.java
> +        mRecycler = (RecyclerView) view.findViewById(R.id.articles_recyclerview);
Extract to a `bindView()` method and call in `initializeUI()`

2016-12-07 03:49 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/grinnell_publications_android/Fragments/ProfileFragment.java
> +        RealmAuthor richard = new RealmAuthor("Rick and Morty", null, pubs, null);
Please use proper variable names

2016-12-07 03:49 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/grinnell_publications_android/Fragments/ProfileFragment.java
> +        RealmPublication snb = new RealmPublication("S&B", 0, null, null, null);
Proper variable names

2016-12-07 03:50 UTC, LarryAsante commented on app/src/main/res/values/colors.xml
> +
Unnecessary whitespace. Take it off

2016-12-07 03:50 UTC, LarryAsante commented on app/src/main/res/values/styles.xml
> +
Unnecessary whitespace. Take it off

2016-12-07 03:51 UTC, LarryAsante requested changes
Great job getting it done, Mattori. Please check the comments and make the appropriate changes. Thanks for all your work!

2016-12-17 21:19 UTC, PsychicNoodles commented
@LarryAsante Please take a close look at the usage of `onDestroyView` and the update to the `initializeUI` interface method (I accidentally typo'd that commit by calling it `initializeView` 😞 )

2017-01-21 01:53 UTC, PsychicNoodles commented
![screenshot_20170120-205204](https://cloud.githubusercontent.com/assets/1944082/22170924/7d4545ba-df52-11e6-9a27-e0fa5c114320.png)
![screenshot_20170120-205219](https://cloud.githubusercontent.com/assets/1944082/22170925/7e59efd2-df52-11e6-8f9f-6f7196a3c07b.png)

2017-01-23 16:34 UTC, merged