Add coordinator layout
GrinnellAppDev/Publications-Android pull request #9
Opened 2016-11-06 20:52 UTC by YazanKittaneh

Added CoordinatorLayout.
Removed article detail from the PR.

2016-11-07 21:34 UTC, YazanKittaneh commented
<img width="989" alt="after" src="https://cloud.githubusercontent.com/assets/6397132/20076872/ab2796be-a4ff-11e6-9625-313400d56fd0.png">
<img width="1005" alt="before" src="https://cloud.githubusercontent.com/assets/6397132/20076873/ab2a9102-a4ff-11e6-8627-8f0a6fe628ea.png">

2016-11-07 21:38 UTC, YazanKittaneh commented
![current app status](https://cloud.githubusercontent.com/assets/6397132/20077025/47e539a2-a500-11e6-952e-6d7bbd81e2d5.png)

2016-11-08 03:18 UTC, LarryAsante commented on .idea/gradle.xml
> +        <option name="distributionType" value="LOCAL" />
Please keep the gradle distribution type as `DEFAULT_WRAPPED`

2016-11-08 03:20 UTC, LarryAsante commented on app/build.gradle
> +    testCompile 'org.mockito:mockito-core:1.9.5'
Nit-picking here: Make sure your changes really reflect what you said you're doing. Moving the mockito  and junit dependency around are not particularly the relevant changes here. This is distracting to anyone reviewing the code :)

2016-11-08 03:37 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/grinnell_publications_android/Activities/MainActivity.java
>      @Bind(R.id.navigation_view) NavigationView navigationView;
Nit-picking here again: How about we make all our member variables in this format : eg. `NavigationView nagivationView` will now become `NavigationView mNavigationView`. This way, we can easily differentiate b/n member variable and non-member variables.

2016-11-08 03:37 UTC, LarryAsante commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/main_content"
Nice! I like that you keep the naming syntax here!

2016-11-08 03:38 UTC, LarryAsante requested changes
Nice start, @YazanKittaneh ! A few nit-picking comments but it all looks good. Kindly review them and make the changes and we should be good to go!

2016-11-13 20:15 UTC, closed without merging